### ISSUE TITLE
522 Connection timed out https://painet-faucet.mempoolnode.live/

### ISSUE THREAD

**Issue by zhangxiaofeng05** [mgpai22/paiNet#1]
https://painet-faucet.mempoolnode.live/

![Xnip2022-11-02_11-57-49](https://user-images.githubusercontent.com/32127451/199392282-b01b914a-cec7-4a5d-b409-5a5faddaa825.jpg)

**Comment by mgpai22** [comment]
Hey I am performing server maintenance. This will be down for a few days.
